export const ACTION = {
    //staff
    EQUIPMENT_MANAGEMENT_VIEW: "EQUIPMENT_MANAGEMENT_VIEW",
    EQUIPMENT_MANAGEMENT_ADD: "EQUIPMENT_MANAGEMENT_ADD",
    EQUIPMENT_MANAGEMENT_EDIT: "EQUIPMENT_MANAGEMENT_EDIT",
    EQUIPMENT_MANAGEMENT_ALLOCATION: "EQUIPMENT_MANAGEMENT_ALLOCATION",
    EQUIPMENT_MANAGEMENT_RECALL: "EQUIPMENT_MANAGEMENT_RECALL",
    EQUIPMENT_MANAGEMENT_HISTORY_LOG: "EQUIPMENT_MANAGEMENT_HISTORY_LOG",
    //manager
    EQUIPMENT_MANAGEMENT_EXPORT: "EQUIPMENT_MANAGEMENT_EXPORT",
    EQUIPMENT_SETTING_SUPLLIER_LIST: "EQUIPMENT_SETTING_SUPLLIER_LIST",
    EQUIPMENT_SETTING_SUPLLIER_ADD: "EQUIPMENT_SETTING_SUPLLIER_ADD",
    EQUIPMENT_SETTING_SUPLLIER_EDIT: "EQUIPMENT_SETTING_SUPLLIER_EDIT",
    EQUIPMENT_SETTING_SUPLLIER_HISTORY_LOG: "EQUIPMENT_SETTING_SUPLLIER_HISTORY_LOG",
    EQUIPMENT_SETTING_TYPE_LIST: "EQUIPMENT_SETTING_TYPE_LIST",
    EQUIPMENT_SETTING_TYPE_ADD: "EQUIPMENT_SETTING_TYPE_ADD",
    EQUIPMENT_SETTING_TYPE_EDIT: "EQUIPMENT_SETTING_TYPE_EDIT",
    EQUIPMENT_SETTING_TYPE_HISTORY_LOG: "EQUIPMENT_SETTING_TYPE_HISTORY_LOG",
    EQUIPMENT_SETTING_BRAND_LIST: "EQUIPMENT_SETTING_BRAND_LIST",
    EQUIPMENT_SETTING_BRAND_ADD: "EQUIPMENT_SETTING_BRAND_ADD",
    EQUIPMENT_SETTING_BRAND_EDIT: "EQUIPMENT_SETTING_BRAND_EDIT",
    EQUIPMENT_SETTING_BRAND_HISTORY_LOG: "EQUIPMENT_SETTING_BRAND_HISTORY_LOG",
    EQUIPMENT_SETTING_GENERAL_VIEW: "EQUIPMENT_SETTING_GENERAL_VIEW",
    EQUIPMENT_SETTING_GENERAL_UPDATE: "EQUIPMENT_SETTING_GENERAL_UPDATE"
}
export const PERMISSION = {
    EQUIPMENT_ALLOCATOR: 'EQUIPMENT_ALLOCATOR',
    EQUIPMENT_MANAGER: "EQUIPMENT_MANAGER",
}

export const PERMISSION_ACTION = {
    [PERMISSION.EQUIPMENT_ALLOCATOR]: [
        ACTION.EQUIPMENT_MANAGEMENT_VIEW,
        ACTION.EQUIPMENT_MANAGEMENT_ADD,
        ACTION.EQUIPMENT_MANAGEMENT_EDIT,
        ACTION.EQUIPMENT_MANAGEMENT_ALLOCATION,
        ACTION.EQUIPMENT_MANAGEMENT_RECALL,
        ACTION.EQUIPMENT_MANAGEMENT_HISTORY_LOG
    ],
    [PERMISSION.EQUIPMENT_MANAGER]: [
        ACTION.EQUIPMENT_MANAGEMENT_VIEW,
        ACTION.EQUIPMENT_MANAGEMENT_ADD,
        ACTION.EQUIPMENT_MANAGEMENT_EDIT,
        ACTION.EQUIPMENT_MANAGEMENT_ALLOCATION,
        ACTION.EQUIPMENT_MANAGEMENT_RECALL,
        ACTION.EQUIPMENT_MANAGEMENT_HISTORY_LOG,
        ACTION.EQUIPMENT_MANAGEMENT_EXPORT,
        ACTION.EQUIPMENT_SETTING_SUPLLIER_LIST,
        ACTION.EQUIPMENT_SETTING_SUPLLIER_ADD,
        ACTION.EQUIPMENT_SETTING_SUPLLIER_EDIT,
        ACTION.EQUIPMENT_SETTING_SUPLLIER_HISTORY_LOG,
        ACTION.EQUIPMENT_SETTING_TYPE_LIST,
        ACTION.EQUIPMENT_SETTING_TYPE_ADD,
        ACTION.EQUIPMENT_SETTING_TYPE_EDIT,
        ACTION.EQUIPMENT_SETTING_TYPE_HISTORY_LOG,
        ACTION.EQUIPMENT_SETTING_BRAND_LIST,
        ACTION.EQUIPMENT_SETTING_BRAND_ADD,
        ACTION.EQUIPMENT_SETTING_BRAND_EDIT,
        ACTION.EQUIPMENT_SETTING_BRAND_HISTORY_LOG,
        ACTION.EQUIPMENT_SETTING_GENERAL_VIEW,
        ACTION.EQUIPMENT_SETTING_GENERAL_UPDATE
    ],
}