export const MAX_FILE_SEND_AT_TIME = 6;
export const CONVERSATION_LIMIT = 10;
export const MESSAGE_LIMIT = 20;
export const COMMON_LIMIT = 10;
export const WAIT_TO_PROCESS_TIMEOUT = 1*60;
export const GUEST_PREFIX = "Guest"
export const GUEST_LABEL = "Khách hàng tiềm năng"
export const PING_INTERVAL = 30*1000;
export const MAX_PRODUCT_IMAGE = 4;
export const DEFAULT_CHAT_PAGE_TITLE = "Thuocsi.vn Chat"
export const CHANGE_PAGE_TITLE_INTERVAL = 1000;